# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fcc22ffe3a8a8d1bf9b1b0b0a13b1fdc"
name = "test1"
handle = "test1-1267"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "store-chec.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
